/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as OrgRouteImport } from './routes/org'
import { Route as GovRouteImport } from './routes/gov'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as OrgIndexRouteImport } from './routes/org.index'
import { Route as GovIndexRouteImport } from './routes/gov.index'
import { Route as StudentSearchRouteImport } from './routes/student.search'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentPathRouteImport } from './routes/student.path'
import { Route as StudentNetworkRouteImport } from './routes/student.network'
import { Route as StudentHeatmapRouteImport } from './routes/student.heatmap'
import { Route as OrgSearchRouteImport } from './routes/org.search'
import { Route as OrgNetworkRouteImport } from './routes/org.network'
import { Route as OrgIdentityRouteImport } from './routes/org.identity'
import { Route as OrgHeatmapRouteImport } from './routes/org.heatmap'
import { Route as OrgCreateRouteImport } from './routes/org.create'
import { Route as OrgActionsRouteImport } from './routes/org.actions'
import { Route as GovTrendsRouteImport } from './routes/gov.trends'
import { Route as GovSearchRouteImport } from './routes/gov.search'
import { Route as GovRegionRouteImport } from './routes/gov.region'
import { Route as GovProfilesMapRouteImport } from './routes/gov.profiles-map'
import { Route as GovOrgsMapRouteImport } from './routes/gov.orgs-map'
import { Route as GovNetworkRouteImport } from './routes/gov.network'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const GovRoute = GovRouteImport.update({
  id: '/gov',
  path: '/gov',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const OrgIndexRoute = OrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgRoute,
} as any)
const GovIndexRoute = GovIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GovRoute,
} as any)
const StudentSearchRoute = StudentSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPathRoute = StudentPathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNetworkRoute = StudentNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHeatmapRoute = StudentHeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => StudentRoute,
} as any)
const OrgSearchRoute = OrgSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => OrgRoute,
} as any)
const OrgNetworkRoute = OrgNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => OrgRoute,
} as any)
const OrgIdentityRoute = OrgIdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => OrgRoute,
} as any)
const OrgHeatmapRoute = OrgHeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => OrgRoute,
} as any)
const OrgCreateRoute = OrgCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => OrgRoute,
} as any)
const OrgActionsRoute = OrgActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => OrgRoute,
} as any)
const GovTrendsRoute = GovTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => GovRoute,
} as any)
const GovSearchRoute = GovSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => GovRoute,
} as any)
const GovRegionRoute = GovRegionRouteImport.update({
  id: '/region',
  path: '/region',
  getParentRoute: () => GovRoute,
} as any)
const GovProfilesMapRoute = GovProfilesMapRouteImport.update({
  id: '/profiles-map',
  path: '/profiles-map',
  getParentRoute: () => GovRoute,
} as any)
const GovOrgsMapRoute = GovOrgsMapRouteImport.update({
  id: '/orgs-map',
  path: '/orgs-map',
  getParentRoute: () => GovRoute,
} as any)
const GovNetworkRoute = GovNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => GovRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gov': typeof GovRouteWithChildren
  '/org': typeof OrgRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/gov/network': typeof GovNetworkRoute
  '/gov/orgs-map': typeof GovOrgsMapRoute
  '/gov/profiles-map': typeof GovProfilesMapRoute
  '/gov/region': typeof GovRegionRoute
  '/gov/search': typeof GovSearchRoute
  '/gov/trends': typeof GovTrendsRoute
  '/org/actions': typeof OrgActionsRoute
  '/org/create': typeof OrgCreateRoute
  '/org/heatmap': typeof OrgHeatmapRoute
  '/org/identity': typeof OrgIdentityRoute
  '/org/network': typeof OrgNetworkRoute
  '/org/search': typeof OrgSearchRoute
  '/student/heatmap': typeof StudentHeatmapRoute
  '/student/network': typeof StudentNetworkRoute
  '/student/path': typeof StudentPathRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/search': typeof StudentSearchRoute
  '/gov/': typeof GovIndexRoute
  '/org/': typeof OrgIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gov/network': typeof GovNetworkRoute
  '/gov/orgs-map': typeof GovOrgsMapRoute
  '/gov/profiles-map': typeof GovProfilesMapRoute
  '/gov/region': typeof GovRegionRoute
  '/gov/search': typeof GovSearchRoute
  '/gov/trends': typeof GovTrendsRoute
  '/org/actions': typeof OrgActionsRoute
  '/org/create': typeof OrgCreateRoute
  '/org/heatmap': typeof OrgHeatmapRoute
  '/org/identity': typeof OrgIdentityRoute
  '/org/network': typeof OrgNetworkRoute
  '/org/search': typeof OrgSearchRoute
  '/student/heatmap': typeof StudentHeatmapRoute
  '/student/network': typeof StudentNetworkRoute
  '/student/path': typeof StudentPathRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/search': typeof StudentSearchRoute
  '/gov': typeof GovIndexRoute
  '/org': typeof OrgIndexRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gov': typeof GovRouteWithChildren
  '/org': typeof OrgRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/gov/network': typeof GovNetworkRoute
  '/gov/orgs-map': typeof GovOrgsMapRoute
  '/gov/profiles-map': typeof GovProfilesMapRoute
  '/gov/region': typeof GovRegionRoute
  '/gov/search': typeof GovSearchRoute
  '/gov/trends': typeof GovTrendsRoute
  '/org/actions': typeof OrgActionsRoute
  '/org/create': typeof OrgCreateRoute
  '/org/heatmap': typeof OrgHeatmapRoute
  '/org/identity': typeof OrgIdentityRoute
  '/org/network': typeof OrgNetworkRoute
  '/org/search': typeof OrgSearchRoute
  '/student/heatmap': typeof StudentHeatmapRoute
  '/student/network': typeof StudentNetworkRoute
  '/student/path': typeof StudentPathRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/search': typeof StudentSearchRoute
  '/gov/': typeof GovIndexRoute
  '/org/': typeof OrgIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gov'
    | '/org'
    | '/student'
    | '/gov/network'
    | '/gov/orgs-map'
    | '/gov/profiles-map'
    | '/gov/region'
    | '/gov/search'
    | '/gov/trends'
    | '/org/actions'
    | '/org/create'
    | '/org/heatmap'
    | '/org/identity'
    | '/org/network'
    | '/org/search'
    | '/student/heatmap'
    | '/student/network'
    | '/student/path'
    | '/student/profile'
    | '/student/search'
    | '/gov/'
    | '/org/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gov/network'
    | '/gov/orgs-map'
    | '/gov/profiles-map'
    | '/gov/region'
    | '/gov/search'
    | '/gov/trends'
    | '/org/actions'
    | '/org/create'
    | '/org/heatmap'
    | '/org/identity'
    | '/org/network'
    | '/org/search'
    | '/student/heatmap'
    | '/student/network'
    | '/student/path'
    | '/student/profile'
    | '/student/search'
    | '/gov'
    | '/org'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/gov'
    | '/org'
    | '/student'
    | '/gov/network'
    | '/gov/orgs-map'
    | '/gov/profiles-map'
    | '/gov/region'
    | '/gov/search'
    | '/gov/trends'
    | '/org/actions'
    | '/org/create'
    | '/org/heatmap'
    | '/org/identity'
    | '/org/network'
    | '/org/search'
    | '/student/heatmap'
    | '/student/network'
    | '/student/path'
    | '/student/profile'
    | '/student/search'
    | '/gov/'
    | '/org/'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GovRoute: typeof GovRouteWithChildren
  OrgRoute: typeof OrgRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gov': {
      id: '/gov'
      path: '/gov'
      fullPath: '/gov'
      preLoaderRoute: typeof GovRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/org/': {
      id: '/org/'
      path: '/'
      fullPath: '/org/'
      preLoaderRoute: typeof OrgIndexRouteImport
      parentRoute: typeof OrgRoute
    }
    '/gov/': {
      id: '/gov/'
      path: '/'
      fullPath: '/gov/'
      preLoaderRoute: typeof GovIndexRouteImport
      parentRoute: typeof GovRoute
    }
    '/student/search': {
      id: '/student/search'
      path: '/search'
      fullPath: '/student/search'
      preLoaderRoute: typeof StudentSearchRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/path': {
      id: '/student/path'
      path: '/path'
      fullPath: '/student/path'
      preLoaderRoute: typeof StudentPathRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/network': {
      id: '/student/network'
      path: '/network'
      fullPath: '/student/network'
      preLoaderRoute: typeof StudentNetworkRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/heatmap': {
      id: '/student/heatmap'
      path: '/heatmap'
      fullPath: '/student/heatmap'
      preLoaderRoute: typeof StudentHeatmapRouteImport
      parentRoute: typeof StudentRoute
    }
    '/org/search': {
      id: '/org/search'
      path: '/search'
      fullPath: '/org/search'
      preLoaderRoute: typeof OrgSearchRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/network': {
      id: '/org/network'
      path: '/network'
      fullPath: '/org/network'
      preLoaderRoute: typeof OrgNetworkRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/identity': {
      id: '/org/identity'
      path: '/identity'
      fullPath: '/org/identity'
      preLoaderRoute: typeof OrgIdentityRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/heatmap': {
      id: '/org/heatmap'
      path: '/heatmap'
      fullPath: '/org/heatmap'
      preLoaderRoute: typeof OrgHeatmapRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/create': {
      id: '/org/create'
      path: '/create'
      fullPath: '/org/create'
      preLoaderRoute: typeof OrgCreateRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/actions': {
      id: '/org/actions'
      path: '/actions'
      fullPath: '/org/actions'
      preLoaderRoute: typeof OrgActionsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/gov/trends': {
      id: '/gov/trends'
      path: '/trends'
      fullPath: '/gov/trends'
      preLoaderRoute: typeof GovTrendsRouteImport
      parentRoute: typeof GovRoute
    }
    '/gov/search': {
      id: '/gov/search'
      path: '/search'
      fullPath: '/gov/search'
      preLoaderRoute: typeof GovSearchRouteImport
      parentRoute: typeof GovRoute
    }
    '/gov/region': {
      id: '/gov/region'
      path: '/region'
      fullPath: '/gov/region'
      preLoaderRoute: typeof GovRegionRouteImport
      parentRoute: typeof GovRoute
    }
    '/gov/profiles-map': {
      id: '/gov/profiles-map'
      path: '/profiles-map'
      fullPath: '/gov/profiles-map'
      preLoaderRoute: typeof GovProfilesMapRouteImport
      parentRoute: typeof GovRoute
    }
    '/gov/orgs-map': {
      id: '/gov/orgs-map'
      path: '/orgs-map'
      fullPath: '/gov/orgs-map'
      preLoaderRoute: typeof GovOrgsMapRouteImport
      parentRoute: typeof GovRoute
    }
    '/gov/network': {
      id: '/gov/network'
      path: '/network'
      fullPath: '/gov/network'
      preLoaderRoute: typeof GovNetworkRouteImport
      parentRoute: typeof GovRoute
    }
  }
}

interface GovRouteChildren {
  GovNetworkRoute: typeof GovNetworkRoute
  GovOrgsMapRoute: typeof GovOrgsMapRoute
  GovProfilesMapRoute: typeof GovProfilesMapRoute
  GovRegionRoute: typeof GovRegionRoute
  GovSearchRoute: typeof GovSearchRoute
  GovTrendsRoute: typeof GovTrendsRoute
  GovIndexRoute: typeof GovIndexRoute
}

const GovRouteChildren: GovRouteChildren = {
  GovNetworkRoute: GovNetworkRoute,
  GovOrgsMapRoute: GovOrgsMapRoute,
  GovProfilesMapRoute: GovProfilesMapRoute,
  GovRegionRoute: GovRegionRoute,
  GovSearchRoute: GovSearchRoute,
  GovTrendsRoute: GovTrendsRoute,
  GovIndexRoute: GovIndexRoute,
}

const GovRouteWithChildren = GovRoute._addFileChildren(GovRouteChildren)

interface OrgRouteChildren {
  OrgActionsRoute: typeof OrgActionsRoute
  OrgCreateRoute: typeof OrgCreateRoute
  OrgHeatmapRoute: typeof OrgHeatmapRoute
  OrgIdentityRoute: typeof OrgIdentityRoute
  OrgNetworkRoute: typeof OrgNetworkRoute
  OrgSearchRoute: typeof OrgSearchRoute
  OrgIndexRoute: typeof OrgIndexRoute
}

const OrgRouteChildren: OrgRouteChildren = {
  OrgActionsRoute: OrgActionsRoute,
  OrgCreateRoute: OrgCreateRoute,
  OrgHeatmapRoute: OrgHeatmapRoute,
  OrgIdentityRoute: OrgIdentityRoute,
  OrgNetworkRoute: OrgNetworkRoute,
  OrgSearchRoute: OrgSearchRoute,
  OrgIndexRoute: OrgIndexRoute,
}

const OrgRouteWithChildren = OrgRoute._addFileChildren(OrgRouteChildren)

interface StudentRouteChildren {
  StudentHeatmapRoute: typeof StudentHeatmapRoute
  StudentNetworkRoute: typeof StudentNetworkRoute
  StudentPathRoute: typeof StudentPathRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentSearchRoute: typeof StudentSearchRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentHeatmapRoute: StudentHeatmapRoute,
  StudentNetworkRoute: StudentNetworkRoute,
  StudentPathRoute: StudentPathRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentSearchRoute: StudentSearchRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GovRoute: GovRouteWithChildren,
  OrgRoute: OrgRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
